version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  "test":
    parameters:
      version:
        type: string
      modules:
        type: boolean
        default: true
    docker:
      - image: "cimg/go:<< parameters.version >>"
    working_directory: ~/go/src/github.com/bmf-san/go-router-benchmark
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: "Go version"
          command: go version
      - run:
          name: "Fetch dependencies"
          command: go mod download
      - run:
          name: "Run gofmt"
          command: make gofmt
      - run:
          name: "Run vet"
          command: make vet
      - run:
          name: "Install tools"
          command: make install-tools
      - run:
          name: "Run go staticcheck"
          command: make staticcheck
      - run:
          name: "Run go test-benchmark"
          command: make test-benchmark

workflows:
  tests:
    jobs:
      - test:
          matrix:
            parameters:
              version: ["1.22"]